

services:
  # The "Public" STUN/TURN Server
  stun-server:
    build: 
      context: .
      dockerfile: test/Dockerfile
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"

  create-peer:
    build: 
      context: .
      dockerfile: test/Dockerfile
    privileged: true
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"

  # Router for Side A
  router-a:
    build: 
      context: .
      dockerfile: Dockerfile.router
    privileged: true
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"

  # Client A (Behind NAT A)
  client-a:
    build: 
      context: .
      dockerfile: test/Dockerfile
    privileged: true
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"

  # Router for Side B
  router-b:
    build: 
      context: .
      dockerfile: Dockerfile.router
    privileged: true
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"

  # Client B (Behind NAT B)
  client-b:
    build: 
      context: .
      dockerfile: test/Dockerfile
    privileged: true
    command: >
        sh -c "tail -f /dev/null"
    network_mode: "none"


