
version: "3.7"

services:
  # The "Public" custom STUN Server
  stun-server:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    command: >
        sh -c "
              cd test/stun;
              sleep 6;
              python3 -u stun.py
              tail -f /dev/null"
    network_mode: "none"

  create-peer:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
        sh -c "
              cd src;
              tail -f /dev/null"
    network_mode: "none"

  router-net:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true
    command: >
        sh -c "
              sleep 3;
              iptables -A FORWARD -j ACCEPT;
              tail -f /dev/null"
    network_mode: "none"

  # Router for Side A
  router-a:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true

    command: >
        sh -c "
              sleep 3;
              iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT;
              iptables -t nat -A PREROUTING -i eth1 -j DNAT --to-destination 192.168.1.2;
              iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.4.2;
              iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT;
              iptables -A FORWARD -i eth1 -m state --state NEW -j DROP;
              tail -f /dev/null"
    
    # command: >
    #     sh -c "
    #           sleep 3;
    #           iptables -t raw -A PREROUTING -i eth1 -m conntrack --ctstate NEW -j DROP
    #           iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.4.2 --random-fully;
    #           iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT;
    #           iptables -A FORWARD -i eth1 -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT;
    #           iptables -P FORWARD DROP;
    #           tail -f /dev/null"
    # NAT
    # command: >
    #     sh -c "
    #           sleep 3;
    #           iptables -A FORWARD -j ACCEPT;
    #           iptables -t nat -A PREROUTING -i eth1 -j DNAT --to-destination 192.168.1.2;
    #           iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.4.2;
    #           iptables -A INPUT -i eth1 -m state --state ESTABLISHED,RELATED -j ACCEPT;
    #           iptables -A INPUT -i eth1 -m state --state NEW -j DROP;
    #           tail -f /dev/null"
    network_mode: "none"

  # Client A (Behind NAT A)
  client-a:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
      sh -c "cd src;
            tail -f /dev/null"
    network_mode: "none"

  # Router for Side B
  router-b:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true

    command: >
        sh -c "
              sleep 3;
              iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT
              iptables -t nat -A PREROUTING -i eth1 -j DNAT --to-destination 192.168.2.2;
              iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.1.2;
              iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
              iptables -A FORWARD -i eth1 -m state --state NEW -j DROP;
              tail -f /dev/null"

    # command: >
    #     sh -c "
    #           sleep 3;
    #           iptables -t raw -A PREROUTING -i eth1 -m conntrack --ctstate NEW -j DROP;
    #           iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.1.2 --random-fully;
    #           iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT;
    #           iptables -A FORWARD -i eth1 -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT;
    #           iptables -P FORWARD DROP;
    #           tail -f /dev/null"
    # NAT
    # command: >
    #     sh -c "
    #           sleep 3;
    #           iptables -A FORWARD -j ACCEPT;
    #           iptables -t nat -A PREROUTING -i eth1 -j DNAT --to-destination 192.168.2.2;
    #           iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 172.20.1.2;
    #           iptables -A INPUT -i eth1 -m state --state ESTABLISHED,RELATED -j ACCEPT;
    #           iptables -A INPUT -i eth1 -m state --state NEW -j DROP;
    #           tail -f /dev/null"
    network_mode: "none"

  # Client B (Behind NAT B)
  client-b:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
      sh -c "cd src;
            tail -f /dev/null"
    network_mode: "none"


