
version: "3.7"

services:
  # The "Public" STUN/TURN Server
  stun-server:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    command: >
        sh -c "
              cd test/stun;
              sleep 6;
              python3 -u stun.py
              tail -f /dev/null"
    network_mode: "none"

  create-peer:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
        sh -c "
              cd src;
              sleep 10;
              python3 -u main.py create --run --ip 10.0.0.1 --sync Gossip < ../test/create-nat-scenario.txt
              tail -f /dev/null"
    network_mode: "none"

  router-net:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true
    command: >
        sh -c "
              sleep 3;
              iptables -A FORWARD -j ACCEPT;
              tail -f /dev/null"
    network_mode: "none"

  # Router for Side A
  router-a:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true
    # command: >
    #     sh -c "tail -f /dev/null"
    command: >
        sh -c "
              sleep 3;
              iptables -t nat -A PREROUTING -i eth1 -p udp -j DNAT --to-destination 192.168.1.2;
              iptables -t nat -A POSTROUTING -o eth1 -p udp -j SNAT --to-source 172.20.4.2;
              iptables -t nat -A PREROUTING -i eth1 -p tcp -j DNAT --to-destination 192.168.1.2;
              iptables -t nat -A POSTROUTING -o eth1 -p tcp -j SNAT --to-source 172.20.4.2;
              iptables -A FORWARD -j ACCEPT;
              tail -f /dev/null"
    network_mode: "none"

  # Client A (Behind NAT A)
  client-a:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
      sh -c "cd src;
            sleep 13;
            python3 -u main.py join 172.20.3.2 --port 2020 --run --ip 10.0.0.2 < ../test/join-hang_scenario.txt;
            tail -f /dev/null"
    network_mode: "none"

  # Router for Side B
  router-b:
    build: 
      context: .
      dockerfile: test/Dockerfile.router
    privileged: true
    # command: >
    #     sh -c "tail -f /dev/null"
    command: >
        sh -c "
              sleep 3;
              iptables -t nat -A PREROUTING -i eth1 -p udp -j DNAT --to-destination 192.168.2.2;
              iptables -t nat -A POSTROUTING -o eth1 -p udp -j SNAT --to-source 172.20.1.2;
              iptables -t nat -A PREROUTING -i eth1 -p tcp -j DNAT --to-destination 192.168.2.2;
              iptables -t nat -A POSTROUTING -o eth1 -p tcp -j SNAT --to-source 172.20.1.2;
              iptables -A FORWARD -j ACCEPT;
              tail -f /dev/null"
    network_mode: "none"

  # Client B (Behind NAT B)
  client-b:
    build: 
      context: .
      dockerfile: test/Dockerfile.main
    privileged: true
    command: >
      sh -c "cd src;
            sleep 16;
            python3 -u main.py join 172.20.3.2 --port 3030 --run --ip 10.0.0.3 < ../test/join-hang_scenario.txt;
            tail -f /dev/null"
    network_mode: "none"


